export const FAMILIAR_PHRASES = [
  "Backend developer near me",
  "Best API Development",
  "System Architecture Expert",
  "Contact us for server solutions",
  "Best Java Developer",
  "Experienced Backend Developers",
  "Database optimization solutions",
  "Spring Boot Development",
  "Custom API Development",
  "VPS Setup Services",
  "Mobile App Development",
  "Hibernate Solutions Provider",
  "Stripe Integration Experts",
  "We are providing the work on time",
  "Trusted Backend Partner",
  "Enterprise Software Architecture",
] as const;
